### ISSUE TITLE
Move chat handler into a module

### ISSUE THREAD

**Issue by Innectic** [ifydev/Permissify#43]
MODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULE

**Comment by Alkali-Metal** [comment]
MODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULEMODULE
